# Generated by Django 4.1.7 on 2023-03-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
