# Generated by Django 4.1.7 on 2023-03-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
