# Generated by Django 4.1.7 on 2023-03-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0007_alter_orders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
