# Generated by Django 4.1.7 on 2023-03-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
