# Generated by Django 4.1.7 on 2023-03-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0012_rename_user_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
