# Generated by Django 4.1.7 on 2023-03-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0014_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
